export const ELECTION_STEPS = [
  { step:1, icon:'📋', titleEn:'Voter Registration', titleTa:'வாக்காளர் பதிவு',
    descEn:'Fill Form 6 online at voters.eci.gov.in or at your local BLO office. Submit proof of age, identity, and address. You will receive an Elector Photo Identity Card (EPIC/Voter ID).',
    descTa:'voters.eci.gov.in இல் ஆன்லைனில் Form 6 நிரப்பவும். வயது, அடையாளம் மற்றும் முகவரி சான்று சமர்ப்பிக்கவும்.',
    videoId:'voter_registration', color:'#ff6b1a' },
  { step:2, icon:'📢', titleEn:'Election Announcement', titleTa:'தேர்தல் அறிவிப்பு',
    descEn:'The Election Commission of India announces election dates. The Model Code of Conduct comes into effect immediately. Candidates file nominations and campaigns begin.',
    descTa:'இந்திய தேர்தல் ஆணையம் தேர்தல் தேதிகளை அறிவிக்கிறது. நடத்தை விதிமுறை உடனடியாக அமலுக்கு வருகிறது.',
    videoId:'election_stages', color:'#3b82f6' },
  { step:3, icon:'🗳️', titleEn:'Polling Day', titleTa:'வாக்குப்பதிவு நாள்',
    descEn:'Carry your Voter ID to the assigned polling booth. Your name is verified on the electoral roll. Press the button next to your chosen candidate on the EVM. A VVPAT slip confirms your vote.',
    descTa:'உங்கள் வாக்காளர் அட்டையை நியமிக்கப்பட்ட வாக்குச் சாவடிக்கு எடுத்துச் செல்லுங்கள். EVM இல் உங்கள் தேர்ந்தெடுத்த வேட்பாளரின் பொத்தானை அழுத்துங்கள்.',
    videoId:'evm_voting', color:'#138808' },
  { step:4, icon:'📊', titleEn:'Vote Counting & Results', titleTa:'வாக்கு எண்ணிக்கை மற்றும் முடிவுகள்',
    descEn:'On counting day, EVMs are opened and votes counted under strict supervision. The candidate with the highest votes wins (First Past The Post). Results are declared officially.',
    descTa:'எண்ணிக்கை நாளில் EVM கள் திறக்கப்பட்டு கடுமையான கண்காணிப்பின் கீழ் வாக்குகள் எண்ணப்படுகின்றன.',
    videoId:'counting_results', color:'#8b5cf6' },
  { step:5, icon:'🏛️', titleEn:'Government Formation', titleTa:'அரசு அமைப்பு',
    descEn:'The party or coalition with a majority (272+ seats in Lok Sabha) forms the government. The President invites the majority party leader to become Prime Minister.',
    descTa:'பெரும்பான்மை பெறும் கட்சி அரசை அமைக்கிறது. குடியரசுத் தலைவர் அவர்களை பிரதமராக நியமிக்கிறார்.',
    videoId:null, color:'#ec4899' },
];
